- name: Install ssmtp
  apt: name={{ item }} state=present
  with_items:
    - ssmtp

- name: Install ssmtp.conf template
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    mode: 0640
    owner: root
    group: root

- name: Install revaliases template
  template:
    src: revaliases.j2
    dest: /etc/ssmtp/revaliases
    mode: 0640
    owner: root
    group: root
